#Eureka-client 启动端口
server:
  port: 10022
  #指定访问项目路径的项目名(不加访问路径是：http://localhost:10022/test/hello)
  servlet:
    context-path: /content

#注册中心 服务名称（eureka-server没意义，eureka-client中很有用）
spring:
  application:
    name: content-module-lbj
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制） 默认8
        max-idle: 8 #连接池中的最大空闲连接 默认8
        min-idle: 0 #连接池中的最小空闲连接 默认0
        #max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
  datasource:
    url: jdbc:mysql://localhost:3306/lee?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

#eureka-client 配置
eureka:
  instance:
    #设置true，则跳转链接为微服务启动机器的ip+端口(注：eureka会自动获取本机ip和该服务端口号)，设为false为微服务启动机器的名称+端口
    prefer-ip-address: true
    #这个配置是相对路径（eureka会自动识别路径）, status-page-url 是绝对路径（不同项目是这个）
    status-page-url-path: /swagger-ui.html
  client:
    #eureka-server服务地址(eureka-server项目中)
    service-url:
      defaultZone: http://localhost:10001/eureka/

#开启Hystrix，Feign是自带断路器的，在D版本的Spring Cloud之后，它没有默认打开。需要在配置文件中配置打开它
feign:
  hystrix:
    enabled: true

content:
  addres: redis://127.0.0.1:6379, redis://127.0.0.1:7001, redis://127.0.0.1:7002